---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: 11.18

platforms:
  - name: centos-7.1
    driver:
      network:
      - ["forwarded_port", {guest: 4444, host: 4444}]
      - ["forwarded_port", {guest: 5555, host: 5555}]

  - name: ubuntu-14.04
    driver:
      network:
      - ["forwarded_port", {guest: 4444, host: 4445}]
      - ["forwarded_port", {guest: 5555, host: 5556}]

  - name: windows-2012r2
    driver:
      box: dhoer/windows-2012r2
      network:
      - ["forwarded_port", {guest: 4444, host: 4446}]
      - ["forwarded_port", {guest: 5555, host: 5557}]
    attributes:
      java:
        windows:
          # export WIN_JDK_URL=http://example.com/path/to/jdk-8u51-windows-i586.exe; kitchen dia
          url: <%= ENV['WIN_JDK_URL'] %>
      selenium:
        windows:
          java: C:\\Program Files (x86)\\Java\\jdk1.8.0_51\\bin\\java.exe

suites:
  - name: selenium_test
    run_list:
      - recipe[selenium_test::package]
      - recipe[selenium_test::java]
      - recipe[selenium_test::hub]
      - recipe[selenium_test::node]
      - recipe[selenium_test::htmlunit]
    attributes:
      java:
        jdk_version: '7'
